packageExtensions:
  gatsby-cli@*:
    dependencies:
      typescript: "*"
  gatsby-core-utils@*:
    dependencies:
      typescript: "*"
  gatsby-plugin-root-import@*:
    dependencies:
      prettier: "*"
  gatsby@*:
    dependencies:
      "@babel/types": "*"
      babel-plugin-styled-components: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.js
