name: Build Image

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [master]

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

      - name: Set up ghost config
        env:
          GHOST_CONFIG: ${{ secrets.GHOST_CONFIG }}
        run: echo "$GHOST_CONFIG" > ghostConfig.json

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/cuhacking/main-website/main-website:latest
