name: Build Image

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [master]

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate package registry
        run: echo "${{ secrets.CONTAINER_TOKEN }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: Set up ghost config
        env:
          GHOST_CONFIG: ${{ secrets.GHOST_CONFIG }}
        run: echo "$GHOST_CONFIG" > ghostConfig.json

      - name: Get tag
        run: git describe --tags >> $BUILD_TAG

      - name: Build and tag image
        run: docker build -t ghcr.io/cuhacking/main-website:${BUILD_TAG} -t ghcr.io/cuhacking/main-website:latest .

      - name: Push image
        if: success()
        run: docker push ghcr.io/cuhacking/main-website
